version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mindfulmeals
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d mindfulmeals"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ../..
      dockerfile: infrastructure/docker/backend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://app_user:secure_password@postgres:5432/mindfulmeals
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secure-jwt-secret
      JWT_REFRESH_SECRET: your-super-secure-refresh-secret
    volumes:
      - ../../backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_data:
